services:
  vulnerable-webapp:
    build:
      context: ../apps/vulnerable-webapp
    image: vuln-web:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
