name: ZAP Baseline DAST

on:
  workflow_dispatch:
  pull_request:

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          cd apps/vulnerable-webapp
          npm ci

      - name: Start vulnerable app
        run: |
          cd apps/vulnerable-webapp
          npm start &
          npx wait-on http://localhost:3000

      - name: Run ZAP Baseline
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:3000'
          cmd_options: '-a -T 60'
          rules_file_name: './tooling/configs/zap-baseline.conf'
          fail_action: false

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            report_html.html
            report_json.json
